# Generated by Django 3.1.3 on 2022-11-27 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mastermind', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Game', 'verbose_name_plural': 'Games'},
        ),
        migrations.AlterModelOptions(
            name='guess',
            options={'verbose_name': 'Guess', 'verbose_name_plural': 'Guesses'},
        ),
    ]
