# Generated by Django 3.1.3 on 2022-11-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastermind', '0002_auto_20221127_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='sequence',
            field=models.CharField(max_length=4),
        ),
    ]
